name: VoiceShell
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: '16.0'

targets:
  VoiceShell:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: VoiceShell
    info:
      path: VoiceShell/Info.plist
      properties:
        CFBundleDisplayName: Voice Hertz
        UILaunchScreen: {}
        NSCameraUsageDescription: Camera access is required for web calls and recording.
        NSMicrophoneUsageDescription: Microphone access is required for web calls and recording.
        NSPhotoLibraryUsageDescription: Photo library access is required for upload features.
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: page.hertz.voice
        PRODUCT_NAME: VoiceShell
        SWIFT_VERSION: 5.10
        TARGETED_DEVICE_FAMILY: '1,2'
        IPHONEOS_DEPLOYMENT_TARGET: '16.0'
